{
     ษออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
     บ      Acest unit apartine programului ARTIST realizat de :      บ
     บ                      Marian Adrian Veteanu                     บ
     บ                Liceul Nicolae Balcescu -  Pitesti              บ
     ศออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
}

unit Fonturi1;

interface

procedure egavgaproc;
procedure boldproc;
procedure europroc;
procedure gothproc;
procedure lcomproc;

implementation

procedure egavgaproc;external;
{$L egavga.obj}
procedure boldproc;external;
{$L bold.obj}
procedure europroc;external;
{$L euro.obj}
procedure gothproc;external;
{$L goth.obj}
procedure lcomproc;external;
{$L lcom.obj}

end.
