{
     ษออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
     บ      Acest unit apartine programului ARTIST realizat de :      บ
     บ                      Marian Adrian Veteanu                     บ
     บ                Liceul Nicolae Balcescu -  Pitesti              บ
     ศออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
}



unit Fonturi2;

interface

procedure littproc;
procedure sansproc;
procedure scriproc;
procedure simpproc;

implementation

procedure littproc;external;
{$L litt.obj}
procedure sansproc;external;
{$L sans.obj}
procedure scriproc;external;
{$L scri.obj}
procedure simpproc;external;
{$L simp.obj}

end.
