{
     ษออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
     บ      Acest unit apartine programului ARTIST realizat de :      บ
     บ                      Marian Adrian Veteanu                     บ
     บ                Liceul Nicolae Balcescu -  Pitesti              บ
     ศออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
}

unit Fonturi3;

interface

procedure tripproc;
procedure tscrproc;

implementation

procedure tripproc;external;
{$L trip.obj}
procedure tscrproc;external;
{$L tscr.obj}

end.
